import {chromium} from 'playwright';import assert from 'node:assert/strict';
const base=process.env.WSC_BASE_URL||'http://127.0.0.1:5174';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1080}});page.on('pageerror',e=>console.log('PAGE ERROR',e.message));await page.goto(base+'/');await page.waitForFunction(()=>window.pu&&document.querySelector('#constraints_settings_opt option[value="divisorsumpairs"]'));
await page.evaluate(()=>{const s=document.getElementById('constraints_settings_opt');s.value='divisorsumpairs';s.dispatchEvent(new Event('change',{bubbles:true}));});
const state=await page.evaluate(()=>({variant:pu.activeSudokuVariant,types:pu.type,edge:pu.sudoku_edge_clue_mode,multi:pu.number_multi_enabled(),mode:pu.mode[pu.mode.qa]}));assert.equal(state.edge,true);assert.deepEqual(state.types,[2,3]);assert.equal(state.multi,false);
const edge=await page.evaluate(()=>{const index=pu.point.findIndex((p,i)=>p&&pu.isKropkiEdge(i)&&p.use===1);const p=pu.point[index],canvas=document.getElementById('canvas'),r=canvas.getBoundingClientRect();return {index,x:r.left+p.x*r.width/canvas.clientWidth,y:r.top+p.y*r.height/canvas.clientHeight};});
await page.mouse.click(edge.x,edge.y);await page.keyboard.press('3');let entry=await page.evaluate(i=>pu.pu_q.number[i],edge.index);assert.equal(String(entry[0]),'3');await page.keyboard.press('2');entry=await page.evaluate(i=>pu.pu_q.number[i],edge.index);assert.equal(String(entry[0]),'32');await page.keyboard.press('Backspace');entry=await page.evaluate(i=>pu.pu_q.number[i],edge.index);assert.equal(String(entry[0]),'3');const cs=await page.evaluate(()=>SudokuSolver.readConstraints(pu));assert.equal(cs.wscRules[0].value,3);assert.equal(cs.wscRules[0].cells.length,2);await page.keyboard.press('Delete');entry=await page.evaluate(i=>pu.pu_q.number[i],edge.index);assert(!entry||entry[0]==='');
await page.evaluate(()=>{const s=document.getElementById('constraints_settings_opt');s.value='classic';s.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await page.evaluate(()=>pu.sudoku_edge_clue_mode),false);
console.log('PASS numeric edge: exact point types, single cursor, click/type/multidigit/backspace/delete, normalized constraint, cleared flag');await browser.close();
