const test=require('node:test'),assert=require('node:assert/strict');
const rules=require('../docs/js/sudoku_variants/wsc_rules.js');
const registry=require('../docs/js/sudoku_variants/index.js');
const solver=require('../docs/js/sudoku_solver.js');
const csp=require('../docs/js/sudoku_csp.js');
const topology=require('../docs/js/wsc_topology.js');
const c=(row,col)=>({row,col}); const line=Array.from({length:9},(_,i)=>c(0,i));
const all=Array.from({length:81},(_,i)=>c(Math.floor(i/9),i%9));
const blank=()=>Array.from({length:9},()=>Array(9).fill(0));
function check(kind,clue,good,bad){test(kind+' accepts valid values and rejects a violating completion',()=>{const q={kind,...clue};assert.equal(rules.valid(q),true);const b=blank();for(const [r,col,v] of good)b[r][col]=v;assert.equal(rules.validate(b,q),true);for(const [r,col,v] of bad)b[r][col]=v;assert.equal(rules.validate(b,q),false);});}
check('hundred',{groups:[[c(0,0),c(0,1)],[c(0,3),c(0,4)]]},[[0,0,2],[0,1,3],[0,3,7],[0,4,7]],[[0,4,6]]);
check('creasing',{cells:line.slice(0,3)},[[0,0,1],[0,1,4],[0,2,8]],[[0,1,9]]);
check('palindrome',{cells:line.slice(0,3)},[[0,0,2],[0,1,4],[0,2,2]],[[0,2,3]]);
check('nothreeinaline',{cells:line.slice(0,3)},[[0,0,1],[0,1,2],[0,2,3]],[[0,1,5]]);
check('tunnel',{cells:line.slice(0,4)},[[0,0,5],[0,1,2],[0,2,3],[0,3,6]],[[0,3,7]]);
check('number5stillalive',{cells:line.slice(0,3)},[[0,0,2],[0,1,4],[0,2,9]],[[0,2,8]]);
check('missingarrow',{cells:line.slice(0,3)},[[0,0,5],[0,1,2],[0,2,3]],[[0,0,6]]);
check('missingthermo',{cells:line.slice(0,3)},[[0,0,7],[0,1,4],[0,2,1]],[[0,1,8]]);
check('transparentkropkipairs',{cells:line.slice(0,2)},[[0,0,3],[0,1,6]],[[0,1,7]]);
check('unordereddistances',{cells:line,x:3,y:7,distance:2},[[0,0,7],[0,2,3]],[[0,2,4],[0,3,3]]);
check('anticlone',{cells:line.slice(0,2),other:[c(1,0),c(1,1)]},[[0,0,3],[0,1,4],[1,0,7],[1,1,6]],[[1,1,5]]);
check('clonealongline',{cells:line.slice(0,2),other:[c(1,0),c(1,1)]},[[0,0,3],[0,1,4],[1,0,4],[1,1,3]],[[1,1,5]]);
check('friends',{cells:line.slice(0,2)},[[0,0,3],[0,1,3]],[[0,1,4]]);
check('enemies',{cells:line.slice(0,2)},[[0,0,3],[0,1,4]],[[0,1,3]]);
check('multidiagonal',{cells:line.slice(0,2)},[[0,0,3],[0,1,4]],[[0,1,3]]);
check('antioutside',{cells:line,digits:[4]},[[0,0,3],[0,1,5],[0,2,6]],[[0,2,4]]);
check('sudokuwithnames',{cells:line,digits:[3,1,7]},[3,4,1,5,7,6,2,8,9].map((d,i)=>[0,i,d]),[[0,2,7],[0,4,1]]);
check('sforsudoku',{cells:[c(0,0)],allowed:[1,3,7]},[[0,0,7]],[[0,0,2]]);
check('trishula',{cells:line.slice(0,3),tips:[c(1,0),c(1,1),c(1,2)]},[[0,0,2],[0,1,5],[0,2,8],[1,0,5],[1,1,8],[1,2,2]],[[1,0,4]]);
check('divisorsumpairs',{cells:line.slice(0,2),value:3},[[0,0,4],[0,1,5]],[[0,1,6]]);
check('neighbouringdisparity',{origin:c(1,1),cells:[c(0,0),c(0,2)]},[[1,1,3],[0,0,2],[0,2,4]],[[0,2,5]]);
check('indextoone',{cells:line,value:2},[[0,1,4],[0,3,1]],[[0,3,5]]);
check('primerunsum',{cells:line,value:10},[1,4,3,7,6,2,5,8,9].map((d,i)=>[0,i,d]),[[0,3,5]]);
check('even',{cells:[c(0,0)]},[[0,0,4]],[[0,0,3]]);
check('odd',{cells:[c(0,0)]},[[0,0,3]],[[0,0,4]]);
test('Magic Sword uses one common threshold for all arrows',()=>{const q={kind:'magicsword',clues:[{cells:line,value:1},{cells:line.map(c=>({...c,row:1})),value:1}]};const b=blank();b[0][0]=4;b[0][1]=6;b[1][0]=5;b[1][1]=7;assert(rules.validate(b,q));b[1][0]=7;b[1][1]=8;assert(!rules.validate(b,q));});
test('Next to x shares one unknown across all clues',()=>{const b=blank();b[0]=[1,2,3,4,5,6,7,8,9];b[1]=[2,1,3,4,5,6,7,8,9];const q={kind:'nexttox',clues:[{cells:line,value:'13'},{cells:line.map(c=>({...c,row:1})),value:'1'}]};assert(rules.validate(b,q));q.clues[1].value='35';assert(!rules.validate(b,q));});
test('Flame Path rejects a completed forbidden barrier',()=>{const b=blank(),q={kind:'flamepath',cells:all};assert(rules.validate(b,q));b[4].fill(5);assert(!rules.validate(b,q));});
test('Fractal requires three different bands in every box mini-row and mini-column',()=>{const b=blank(),q={kind:'fractal',cells:all};b[0][0]=1;b[0][1]=4;b[0][2]=7;assert(rules.validate(b,q));b[0][2]=5;assert(!rules.validate(b,q));});
test('Disguised Queen existential digit cannot be chosen independently per conflict',()=>{const b=blank(),q={kind:'disguisedqueen',cells:all};assert(rules.validate(b,q));for(let d=1;d<=9;d++){let r=Math.floor((d-1)/3)*3,c=((d-1)%3)*3;b[r][c]=d;b[r+1][c+1]=d;}assert(!rules.validate(b,q));});
test('Anti Windoku permits four and rejects five distinct values',()=>{const b=blank(),q={kind:'antiwindoku',cells:all};[1,2,3,4].forEach((d,i)=>b[1+Math.floor(i/3)][1+i%3]=d);assert(rules.validate(b,q));b[2][2]=5;assert(!rules.validate(b,q));});
test('Attack the Leader records every tied closest direction',()=>{const b=Array.from({length:9},()=>Array(9).fill(1));b[4][4]=4;b[3][4]=6;b[4][5]=5;const q={kind:'attacktheleader',origin:c(4,4),cells:all,directions:['up','right']};assert(rules.validate(b,q));q.directions=['up'];assert(!rules.validate(b,q));});
function puzzle(id){return {nx:9,ny:9,nx0:13,ny0:13,space:[0,0,0,0],centerlist:[],point:{},activeSudokuVariants:['classic',id],pu_q:{number:{},symbol:{},surface:{},line:{},killercages:[]}};}
test('WSC descriptors fail closed for missing and malformed clues',()=>{const p=puzzle('trishula');assert(registry.interpretPuzzle(p).diagnostics.length);p.pu_q.wsc2026Clues={trishula:[{cells:[c(90,0)],tips:[]}]};assert(registry.interpretPuzzle(p).diagnostics.length);});
test('Hundred composite emits both base sum and disjoint constraints',()=>{const p=puzzle('disjointhundred');p.pu_q.wsc2026Clues={hundred:[{groups:[[c(0,0),c(0,1)],[c(0,3),c(0,4)]]}]};const cs=solver.readConstraints(p);assert.equal(cs.diagnostics.length,0);assert.equal(cs.wscRules.length,1);assert.equal(cs.diagonalAllDifferent.length,9);assert(cs.supported.includes('disjointhundred'));});
test('WSC constraint is enforced by the actual CSP solve',()=>{const b=Array.from({length:9},(_,r)=>Array.from({length:9},(_,c)=>(r*3+Math.floor(r/3)+c)%9+1));b[0][0]=0;const result=csp.solve(b,{wscRules:[{kind:'odd',cells:[c(0,0)]}]});assert(result);assert.equal(csp.findConflict([[2,...b[0].slice(1)],...b.slice(1)],{baseRows:false,baseCols:false,baseBoxes:false,wscRules:[{kind:'odd',cells:[c(0,0)]}]}).constraint,'wscRules');});
test('Topology solver handles gaps, overlapping cell identity and non-square units',()=>{assert.equal(topology.samurai().values.length,369);assert.equal(topology.samurai().units.length,135);assert.equal(topology.solve({values:[1,2,3,4,5,6,7,8,0],units:[[0,1,2,3,4,5,6,7,8]]}).solutions[0][8],9);assert.equal(topology.solve({values:[1,1],units:[[0,1]]}).status,'invalid');assert.throws(()=>topology.solve({values:[0,0],units:[[0,0]]}));assert.equal(topology.solve({values:[0,0],units:[[0,1]]},{maxNodes:1}).status,'limit');});
test('Missing Thermo permits a branch only when one open end can be its bulb',()=>{const q={kind:'missingthermo',cells:[c(0,0),c(0,1),c(0,2),c(1,1)],paths:[[c(0,0),c(0,1),c(0,2)],[c(0,1),c(1,1)]]},b=blank();b[0][0]=1;b[0][1]=3;b[0][2]=7;b[1][1]=6;assert(rules.validate(b,q));b[0][2]=2;assert(!rules.validate(b,q));});
test('Booklet inventory has correct published totals and valid assets',()=>{const fs=require('fs'),catalog=require('../docs/src/wsc2026/catalog.json');assert.equal(catalog.puzzles.length,95);for(const r of catalog.rounds.filter(r=>r.available&&r.id!==16)){assert.equal(catalog.puzzles.filter(p=>p.round===r.id).reduce((s,p)=>s+p.points,0),r.points,'round '+r.id);}for(const p of catalog.puzzles){assert(p.rules.length>20,p.id);for(const key of ['image','example','solution'])assert(fs.existsSync('docs/public'+p[key]),p.id+' '+key);}});

test('WSC Escape is odd reachability from the centre to all four edges, distinct from legacy Escape',()=>{const b=blank(),q={kind:'wscescape',cells:all};assert(rules.validate(b,q));b[4][4]=2;assert(!rules.validate(b,q));b[4][4]=1;b[0].fill(2);assert(!rules.validate(b,q));b[0][4]=3;assert(rules.validate(b,q));assert.equal(registry.resolve('wscescape').label,'Escape (WSC 2026)');});
