import {chromium} from 'playwright';import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs';import assert from 'node:assert/strict';
const base=process.env.WSC_BASE_URL||'http://127.0.0.1:5174';
const db=new PGlite();await db.exec('create role anon;create role authenticated;');await db.exec(fs.readFileSync('supabase/migrations/20260918000000_wsc2026_practice.sql','utf8'));await db.exec(fs.readFileSync('supabase/migrations/20260919000000_wsc2026_single_team.sql','utf8'));await db.exec('set role anon');
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1280,height:1000}});
async function wire(ctx){await ctx.route('**/rest/v1/rpc/wsc2026_api',async route=>{try{const p=route.request().postDataJSON();const r=await db.query('select public.wsc2026_api($1,$2::uuid,$3::jsonb) as data',[p.p_action,p.p_token,JSON.stringify(p.p_payload)]);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(r.rows[0].data)});}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({message:e.message,code:'P0001'})});}});}
await wire(context);const page=await context.newPage();await page.goto(base+'/wsc2026/');assert.equal(await page.locator('.puzzle-card').count(),0);await page.getByLabel('Password',{exact:true}).fill('wrong');await page.getByRole('button',{name:'Enter',exact:true}).click();await page.getByRole('alert').waitFor();await page.getByLabel('Password',{exact:true}).fill('กู้ชาติ');await page.getByRole('button',{name:'Enter',exact:true}).click();await page.locator('.puzzle-card').first().waitFor();assert.equal(await page.locator('.round-section').count(),11);assert.equal(await page.getByRole('button',{name:'Start timer'}).count(),0);assert.equal(await page.locator('.card-controls button[aria-expanded="true"]').count(),0);await page.locator('.puzzle-card').first().getByRole('button',{name:/Puzzles/}).click();await page.locator('.puzzle-entries summary').first().click();await page.locator('.official').first().waitFor({state:'visible'});await page.getByRole('button',{name:'Your profile'}).click();await page.getByLabel('Username',{exact:true}).fill('alice');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'alice ↗'}).waitFor();
const key=await page.evaluate(()=>localStorage.getItem('wsc2026-device-key'));assert(key);
await page.getByLabel('Round',{exact:true}).selectOption('6');await page.locator('.puzzle-card').first().getByRole('button',{name:'+ Plan'}).click();await page.locator('.puzzle-card').first().getByRole('button',{name:'✓ Planned'}).waitFor();await page.locator('.puzzle-card').first().getByRole('button',{name:'Record time'}).click();await page.getByLabel('Time (minutes:seconds)').fill('12:34');await page.getByRole('button',{name:'Save privately'}).click();await page.locator('.modal').waitFor({state:'hidden'});await page.getByRole('tab',{name:'My records'}).click();await page.getByText('12:34',{exact:true}).waitFor();
await page.getByRole('tab',{name:'Rules & examples'}).click();await page.getByRole('button',{name:'+ Add puzzle'}).click();await page.getByLabel('Title',{exact:true}).fill('My first WSC practice');await page.locator('.panel input[type=file]').first().setInputFiles('docs/public/wsc2026/r06-02-example.png');await page.locator('.panel select').first().selectOption('6');await page.getByRole('button',{name:'Save puzzle'}).click();await page.getByRole('heading',{name:'My first WSC practice'}).waitFor();
await page.getByLabel('Round',{exact:true}).selectOption('1');await page.getByRole('button',{name:'+ Add puzzle'}).click();await page.getByLabel('Title',{exact:true}).fill('Killer practice A');await page.locator('.panel select').first().selectOption('1');await page.getByLabel('Variant',{exact:true}).selectOption('killer');await page.getByLabel('Sudotoku puzzle link (optional)').fill(base+'/#m=edit&p=fixture');await page.locator('.panel input[type=file]').first().setInputFiles('docs/public/wsc2026/r01-02-example.png');await page.getByRole('button',{name:'Save puzzle'}).click();await page.locator('.puzzle-card').filter({has:page.getByRole('heading',{name:'Killer Sudoku',exact:true})}).getByRole('button',{name:/Puzzles/}).click();const link=page.getByRole('link',{name:'2. Killer practice A ↗'});await link.waitFor();assert.equal(await link.getAttribute('target'),'_blank');assert.equal(await link.getAttribute('href'),'/#m=solve&p=fixture');await page.getByPlaceholder('Search names or rules…').fill('Killer practice A');assert.equal(await page.locator('.puzzle-card').count(),1);await page.getByPlaceholder('Search names or rules…').fill('');
await page.getByRole('button',{name:'alice ↗'}).click();await page.getByRole('button',{name:'Download private backup'}).click();
const second=await browser.newContext();await wire(second);const bob=await second.newPage();await bob.goto(base+'/wsc2026/');await bob.getByLabel('Password',{exact:true}).fill('กู้ชาติ');await bob.getByRole('button',{name:'Enter',exact:true}).click();await bob.getByRole('button',{name:'Your profile'}).click();await bob.getByLabel('Username',{exact:true}).fill('bob');await bob.getByRole('button',{name:'Continue',exact:true}).click();await bob.getByRole('button',{name:'bob ↗'}).waitFor();await bob.getByRole('tab',{name:'My records'}).click();assert.equal(await bob.locator('.records article').count(),0);await bob.getByRole('tab',{name:'Rules & examples'}).click();await bob.getByRole('heading',{name:'My first WSC practice'}).waitFor();
await page.getByRole('tab',{name:'My round plan'}).click();await page.reload();await page.getByRole('button',{name:'alice ↗'}).waitFor();
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tmp/wsc2026/revised-mobile.png'});
console.log('PASS password gate, layout, browser + PostgreSQL: create/join group, record time, checklist, image upload, shared puzzles, private records, refresh persistence, backup download');await browser.close();await db.close();
