import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const base=process.env.WSC_BASE_URL || 'http://127.0.0.1:5180';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try {
 await page.goto(base+'/wsc2026/?tab=flower');
 if(await page.getByLabel('Password',{exact:true}).count()){
  await page.getByLabel('Password',{exact:true}).fill('กู้ชาติ');
  await page.getByRole('button',{name:'Enter',exact:true}).click();
 }
 const flower=page.locator('.flower-tool');await flower.waitFor();
 assert.equal(await page.getByRole('tab',{name:'Circular Sudoku',exact:true}).count(),0);
 assert.equal(await flower.locator('img').count(),0);
 assert.equal(await flower.locator('.cell').count(),90);
 assert.ok(await flower.locator('.region-border').count()>0);
 const colors=await flower.locator('.cell').evaluateAll(cells=>[...new Set(cells.map(cell=>cell.style.fill))]);
 assert.ok(colors.length>=4);
 const boardBounds=await flower.locator('svg').boundingBox(),controlBounds=await flower.locator('.answer-controls').boundingBox();
 assert.ok(controlBounds.x>=boardBounds.x+boardBounds.width);
 await flower.locator('.sudoku-keypad .digit-9').click();
 assert.match(await flower.locator('#flower-cell-0').getAttribute('aria-label'),/digit 9/);
 assert.equal(await flower.locator('svg .digit').evaluate(el=>getComputedStyle(el).fontSize),'24px');
 await flower.getByRole('button',{name:'Delete selected cell',exact:true}).click();
 assert.match(await flower.locator('#flower-cell-0').getAttribute('aria-label'),/empty/);
 await flower.getByRole('button',{name:'Undo',exact:true}).click();
 assert.match(await flower.locator('#flower-cell-0').getAttribute('aria-label'),/digit 9/);
 await flower.locator('#flower-cell-1').press('x');
 await flower.locator('.sudoku-keypad .digit-2').click();
 assert.equal(await flower.locator('.notes').textContent(),'2');
 await flower.getByRole('button',{name:'Undo',exact:true}).click();
 assert.equal(await flower.locator('.notes').count(),0);
 await flower.locator('.mode-normal').click();
 await flower.getByRole('button',{name:'Generate unique puzzle',exact:true}).click();
 const status=await flower.locator('.status').innerText();assert.match(status,/uniquely solvable/);
 const clues=Number(status.match(/with (\d+) clues/)[1]);
 assert.equal(await flower.locator('svg .digit').count(),clues);
 assert.equal(await flower.locator('.solved-digit').count(),0);
 mkdirSync('output/screenshots',{recursive:true});
 await flower.screenshot({path:'output/screenshots/flower-controls-layout.png'});
 await page.getByRole('tab',{name:'Pentagram Sudoku',exact:true}).click();
 const pentagram=page.locator('.pentagram-tool');await pentagram.waitFor();
 assert.equal(await pentagram.locator('select').count(),0);
 await pentagram.locator('.digit-9').click();
 assert.match(await pentagram.locator('#pentagram-0').getAttribute('aria-label'),/digit 9/);
 await pentagram.getByRole('button',{name:'Delete selected cell',exact:true}).click();
 await pentagram.getByRole('button',{name:'Undo',exact:true}).click();
 assert.match(await pentagram.locator('#pentagram-0').getAttribute('aria-label'),/digit 9/);
 await pentagram.getByRole('button',{name:'Generate unique puzzle',exact:true}).click();
 assert.equal(await pentagram.locator('svg .digit').count(),32);
 await pentagram.screenshot({path:'output/screenshots/pentagram-controls-layout.png'});
 await page.getByRole('tab',{name:'Shifted Sudoku',exact:true}).click();
 await page.getByRole('button',{name:'Add outer ring · 6 grids',exact:true}).click();
 assert.equal(await page.locator('.outer-cell').count(),486);
 await page.locator('.ring-picker button').nth(3).waitFor({timeout:5000});
 assert.equal(await page.locator('.ring-picker button').count(),4);
 await page.locator('.ring-picker button').last().click();
 assert.match(await page.locator('.rotation-controls strong').textContent(),/Outer ring/);
 await page.getByRole('button',{name:'Classic · 3 rings',exact:true}).click();
 assert.equal(await page.locator('.outer-cell').count(),0);
 await page.getByRole('tab',{name:'Hundred Combinations',exact:true}).click();
 const hundred=page.locator('.hundred-tool');await hundred.waitFor();
 assert.equal(await hundred.locator('.pair-matrix button').count(),81);
 await hundred.getByLabel('Find a number or several numbers').fill('24');
 assert.ok(await hundred.locator('.sum').count()>0);
 assert.ok((await hundred.locator('.sum').allTextContents()).every(text=>text.includes('24')));
 await hundred.getByLabel('Find a number or several numbers').fill('');
 await hundred.locator('.pair-matrix button.available').first().click();
 assert.ok(await hundred.locator('.sum').count()>0);
 await hundred.screenshot({path:'output/screenshots/hundred-combinations-layout.png'});
 await page.setViewportSize({width:390,height:844});
 for(const name of ['Flower Sudoku','Pentagram Sudoku','Hundred Combinations']){
  await page.getByRole('tab',{name,exact:true}).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${name} overflows on mobile`);
 }
 assert.deepEqual(errors,[]);
 console.log('Tool layouts, colors, generated blanks, Delete/Undo, notes, outer ring, lookup filters and mobile widths verified.');
} finally {await browser.close();}
