import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1100}}), errors=[];
page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:5180/wsc2026/');
 if(await page.getByLabel('Password',{exact:true}).count()){await page.getByLabel('Password',{exact:true}).fill('กู้ชาติ');await page.getByRole('button',{name:'Enter',exact:true}).click();}
 await page.getByRole('tab',{name:'Shifted Sudoku',exact:true}).click();
 const tool=page.locator('.circular-tool');
 assert.equal(await tool.locator('img').count(),0);
 const cell=tool.locator('#circular-cell-core-0-0');await cell.click();await tool.locator('.digit-7').click();
 assert.match(await cell.getAttribute('aria-label'),/digit 7/);
 const svg=tool.locator('svg');
 const points=await svg.evaluate(svg=>{const matrix=svg.getScreenCTM();const p=angle=>new DOMPoint(600+30*Math.cos(angle*Math.PI/180),600+30*Math.sin(angle*Math.PI/180)).matrixTransform(matrix);return [-70,-48].map(p);});
 const before=await cell.getAttribute('d');
 await page.mouse.move(points[0].x,points[0].y);await page.mouse.down({button:'right'});await page.mouse.move(points[1].x,points[1].y,{steps:8});
 const during=await cell.getAttribute('d');assert.notEqual(during,before);
 await page.mouse.up({button:'right'});await page.waitForTimeout(220);
 assert.notEqual(await cell.getAttribute('d'),during);
 await cell.click();await tool.locator('.digit-4').click();assert.match(await cell.getAttribute('aria-label'),/digit 4/);
 await tool.getByRole('button',{name:'Undo',exact:true}).click();assert.match(await cell.getAttribute('aria-label'),/digit 7/);
 await tool.getByRole('button',{name:'Generate unique puzzle',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.circular-tool .status')?.textContent.includes('uniquely solvable'));assert.match(await tool.locator('.status').textContent(),/uniquely solvable/);
 await page.waitForTimeout(500);
 const scrambled=await tool.locator('#circular-cell-core-3-0').getAttribute('d');
 await tool.getByRole('button',{name:'Solve',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.circular-tool .status')?.textContent.includes('relative ring alignments'));
 assert.match(await tool.locator('.status').textContent(),/relative ring alignments/);
 await page.waitForTimeout(500);
 assert.notEqual(await tool.locator('#circular-cell-core-3-0').getAttribute('d'),scrambled);
 assert.equal(await tool.locator('svg .digit:not(.note)').count(),81);
 await tool.getByRole('button',{name:'Reset',exact:true}).click();
 await tool.getByRole('button',{name:'4 rings · 6 outer grids',exact:true}).click();
 assert.equal(await tool.locator('.outer-cell').count(),486);assert.equal(await tool.locator('.separator').count(),6);assert.equal(await tool.locator('.connector-spoke:not(.third-ring-spoke)').count(),12);
 assert.equal(await tool.locator('.third-ring-spoke').count(),0);
 const gap=await tool.locator('.connector-spoke:not(.third-ring-spoke)').evaluateAll(lines=>lines.every(line=>Math.abs(Math.hypot(line.x1.baseVal.value-600,line.y1.baseVal.value-600)-200)<.01));assert.ok(gap);
 assert.ok(await tool.locator('.connector-spoke').evaluateAll(lines=>lines.every(line=>Math.abs(Math.hypot(line.x2.baseVal.value-600,line.y2.baseVal.value-600)-220)<.01)));
 await tool.getByRole('button',{name:'Generate unique puzzle',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.circular-tool .status')?.textContent.includes('uniquely solvable'));assert.match(await tool.locator('.status').textContent(),/uniquely solvable/);
 assert.equal(await tool.locator('.outer-cell[aria-label*="digit"]').count(),0);
 mkdirSync('output/screenshots',{recursive:true});await tool.screenshot({path:'output/screenshots/shifted-controls-layout.png'});
 await tool.getByRole('button',{name:'Solve',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.circular-tool .status')?.textContent.includes('relative ring alignments'));assert.equal(await tool.locator('svg .digit:not(.note)').count(),567);
 assert.ok(await tool.locator('svg .digit').evaluateAll(texts=>texts.every(text=>text.parentElement.getAttribute('transform')?.startsWith('rotate('))));
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('Shifted keypad, drag preview, snap, entry after rotation, separators, spokes, solver, generator and mobile layout verified.');
}finally{await browser.close();}
