import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1400,height:1100},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5180/wsc2026/?tab=shifted');
 if(await page.getByLabel('Password',{exact:true}).count()){await page.getByLabel('Password',{exact:true}).fill('กู้ชาติ');await page.getByRole('button',{name:'Enter',exact:true}).click();}
 const tool=page.locator('.circular-tool');await tool.getByRole('button',{name:'Reset',exact:true}).click();await tool.getByRole('button',{name:'9×9 square',exact:true}).click();
 const first=tool.locator('#circular-cell-core-0-0'),second=tool.locator('#circular-cell-core-0-1');await first.click();await second.click({modifiers:['Control']});await page.keyboard.press('F3');assert.equal(await tool.getByRole('button',{name:'Solve mode'}).getAttribute('aria-pressed'),'true');
 await page.keyboard.press('Control+4');assert.equal(await tool.locator('.square-note').count(),2);assert.equal(await tool.locator('.square-digit').count(),0);
 await page.keyboard.press('5');assert.equal(await tool.locator('.square-digit').count(),2);assert.equal(await tool.locator('.conflict').count(),2);
 await tool.getByRole('button',{name:'Show conflict: On',exact:true}).click();assert.equal(await tool.locator('.conflict').count(),0);
 const grid=await tool.locator('svg').boundingBox(),header=await tool.locator('header').boundingBox(),tabs=await page.getByRole('tablist').boundingBox();assert.ok(grid.y<header.y&&tabs.y<grid.y);
 await first.click();await page.keyboard.press('F2');assert.equal(await tool.getByRole('button',{name:'Set mode'}).getAttribute('aria-pressed'),'true');await page.keyboard.press('Delete');await page.keyboard.press('Shift+6');assert.equal(await tool.locator('.corner-note').count(),1);
 const band=tool.locator('#circular-cell-core-3-0');const b=await band.boundingBox(),client=await page.context().newCDPSession(page);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await page.waitForTimeout(500);await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+b.width*1.5,y:b.y+b.height/2}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(250);assert.ok((await band.getAttribute('d')).startsWith('M64 '));assert.deepEqual(errors,[]);console.log('Grid-first layout, mode shortcuts, multi-cell input, held notes and conflicts passed.');
 await tool.getByRole('button',{name:'Reset',exact:true}).click();await tool.getByRole('button',{name:'Rings',exact:true}).click();await tool.locator('svg').scrollIntoViewIfNeeded();const before=await band.getAttribute('d'),points=await tool.locator('svg').evaluate(svg=>[-70,-30].map(angle=>{const p=svg.createSVGPoint();p.x=600+90*Math.cos(angle*Math.PI/180);p.y=600+90*Math.sin(angle*Math.PI/180);const q=p.matrixTransform(svg.getScreenCTM());return {x:q.x,y:q.y};}));await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});await page.waitForTimeout(500);await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[points[1]]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(250);assert.notEqual(await band.getAttribute('d'),before);
 await page.getByRole('tab',{name:'Blind Pips',exact:true}).click();const blind=page.locator('.blind-practice');await blind.getByRole('button',{name:'Reset',exact:true}).click();await blind.locator('#blind-cell-0').click();await page.keyboard.press('F2');await page.keyboard.press('2');await blind.locator('#blind-cell-1').click();await page.keyboard.press('2');assert.equal(await blind.locator('.conflict').count(),2);await blind.getByRole('button',{name:'Show conflict: On',exact:true}).click();assert.equal(await blind.locator('.conflict').count(),0);assert.deepEqual(errors,[]);console.log('Mobile ring dragging and pip clue conflicts passed.');
}finally{await browser.close();}
