<script lang="ts">
 import { onMount, tick } from 'svelte';
 import catalog from './wsc2026/catalog.json';
 import SamuraiExample from './wsc2026/SamuraiExample.svelte';
 import SamuraiRules from './wsc2026/SamuraiRules.svelte';
 import BlindPipsPractice from './wsc2026/BlindPipsPractice.svelte';
 import ShiftedSudokuTool from './ShiftedSudokuTool.svelte';
 import FlowerRoundTool from './FlowerRoundTool.svelte';
 import round1Playable from './wsc2026/round1Playable.json';
 import HundredCombinationsTool from './HundredCombinationsTool.svelte';
 import { loadPracticeLinks, playerUrl } from './wsc2026/client';
 let tab=new URLSearchParams(location.search).get('tab')||'booklet', round='', search='', error='', sharedPuzzles:any[]=[], roundType='all';
 $: if(tab==='pentagram')tab='flower';
 $: if (tab==='circular') tab='shifted';
 $: if (!['booklet','blind','shifted','flower','hundred'].includes(tab)) tab='booklet';
 let unlocked=false, password='', passwordError='';
 async function unlock(value=password){passwordError='';try{const response=await fetch('/wsc2026/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:value})});if(!response.ok){passwordError=response.status===401?'Incorrect password.':'Unable to unlock the practice room. Try again.';return;}localStorage.setItem('wsc2026-password',value);unlocked=true;password='';const target=new URLSearchParams(location.search).get('returnTo');if(target){const destination=new URL(target,location.origin);if(destination.origin===location.origin&&destination.pathname.startsWith('/wsc2026/')&&!['/wsc2026/','/wsc2026/access'].includes(destination.pathname)){location.replace(destination.href);return;}}await loadLinks();}catch{passwordError='Could not unlock. Check your connection and browser storage.';}}
 function officialExampleFor(p:any){const puzzle_url=(round1Playable as Record<string,string>)[p.id];return puzzle_url?[{id:`official:${p.id}`,round:p.round,name:'Official example',source:'official',puzzle_url,booklet_ref:p.id,variant_id:p.variantId}]:[];}
 function practiceFor(p:any){return p.source==='practice'?[p]:[...officialExampleFor(p),...practice.filter((q:any)=>q.booklet_ref?q.booklet_ref===p.id:q.round===p.round&&q.variant_id===p.variantId)];}
 function printEntries(section:any){
  if(section.id!==11)return section.entries;
  const relay=section.entries.find((p:any)=>p.source==='booklet');
  if(!relay)return section.entries;
  return [1,2,3].map(index=>({...relay,id:`${relay.id}-grid-${index}`,name:`Relay example · Grid ${index}`,example:`/wsc2026/relay-example-${index}.png`,relayGrid:index}));
 }
 function printRows(section:any){
  const entries=printEntries(section), perRow=printLandscape&&section.id!==2?2:1;
  return Array.from({length:Math.ceil(entries.length/perRow)},(_,index)=>entries.slice(index*perRow,(index+1)*perRow));
 }
 let printMode='', printLandscape=false;
 let openRules:Record<string,boolean>={}, openPuzzles:Record<string,boolean>={};

 $: booklet=catalog.puzzles.map(p=>({...p,source:'booklet'}));
 $: practice=sharedPuzzles.map((p:any)=>({...p,id:'practice:'+p.id,round:p.round_id,name:p.title,source:'practice',example:p.image,solution:p.solution_image,points:null,rules:p.rules}));
 $: cards=[...booklet,...practice.filter((p:any)=>!booklet.some(b=>p.booklet_ref?b.id===p.booklet_ref:b.round===p.round&&b.variantId===p.variant_id))];
 function matchesRoundType(id:number,type=roundType){const team=!!catalog.rounds.find(r=>r.id===id)?.teamRules;return type==='all'||(type==='team'?team:!team);}
 $: visibleRounds=catalog.rounds.filter(r=>matchesRoundType(r.id,roundType));
 $: if(round&&!visibleRounds.some(r=>r.id===Number(round)))round='';
 $: filtered=cards.filter((p:any)=>matchesRoundType(p.round,roundType)&&(!round||p.round===Number(round))&&(!search||`${p.name} ${p.rules}`.toLowerCase().includes(search.toLowerCase())||practice.some((q:any)=>q.round===p.round&&q.variant_id===p.variantId&&`${q.name} ${q.rules}`.toLowerCase().includes(search.toLowerCase()))));
 $: roundSections=catalog.rounds.map(r=>({...r,entries:filtered.filter((p:any)=>p.round===r.id)})).filter(r=>r.entries.length);
 $: printable=[...filtered,...(tab==='booklet'?practice.filter((p:any)=>!filtered.some((q:any)=>q.id===p.id)&&matchesRoundType(p.round,roundType)&&(!round||p.round===Number(round))&&(!search||`${p.name} ${p.rules}`.toLowerCase().includes(search.toLowerCase()))):[])].filter((p:any,i:number,items:any[])=>p.source!=='booklet'||items.findIndex(q=>q.source==='booklet'&&q.example===p.example)===i);
 $: printRoundSections=catalog.rounds.map(r=>({...r,entries:printable.filter((p:any)=>p.round===r.id),catalogEntries:filtered.filter((p:any)=>p.round===r.id)})).filter(r=>r.entries.length||r.catalogEntries.length);
 async function loadLinks(){try{sharedPuzzles=await loadPracticeLinks();}catch(e:any){error=e.message;}}
 onMount(()=>{try{localStorage.removeItem('wsc2026-device-key');localStorage.removeItem('wsc2026-username');const saved=localStorage.getItem('wsc2026-password');if(saved)unlock(saved);}catch{error='Browser storage is unavailable. Enable localStorage to remember the room password.';}});
 async function print(kind:string){printMode=kind;await tick();await Promise.all(Array.from(document.querySelectorAll('.print-area img')).map((img:any)=>img.decode().catch(()=>{})));window.print();printMode='';}
</script>

<svelte:head><title>WSC 2026 · Practice room</title><meta name="description" content="World Sudoku Championship 2026 rules, solved examples and practice tools."/></svelte:head>
 {#if !unlocked}<main class="password-page"><form class="panel" onsubmit={e=>{e.preventDefault();unlock();}}><p class="eyebrow">SUDOTOKU / WSC 2026</p><h1>Practice room</h1><label>Password<input type="password" bind:value={password} required autocomplete="current-password" /></label>{#if passwordError}<p role="alert" class="error">{passwordError}</p>{/if}<button class="primary">Enter</button></form></main>{:else}
<div class="app-shell">
 <main>
  <a class="puzzle-link" href="/wpc2026/">Go to Puzzle ↗</a>
  <div class="tabs" role="tablist" aria-label="Practice sections">{#each [['booklet','Rules & examples'],['blind','Blind Pips'],['shifted','Shifted Sudoku'],['flower','Flower Sudoku'],['hundred','Hundred Combinations']] as item}<button role="tab" aria-selected={tab===item[0]} class:active={tab===item[0]} onclick={()=>{tab=item[0];if(typeof history!=='undefined'){const url=new URL(location.href);url.searchParams.set('tab',item[0]);history.replaceState({},'',url);}}}>{item[1]}</button>{/each}</div>
  {#if error}<p role="alert" class="message error">{error}</p>{/if}
  {#if tab==='booklet'}
   <section class="toolbar"><label>Round type<select aria-label="Round type" bind:value={roundType}><option value="all">Individual &amp; Team</option><option value="individual">Individual</option><option value="team">Team</option></select></label><label>Round<select aria-label="Round" bind:value={round}><option value="">All rounds</option>{#each visibleRounds as r}<option value={String(r.id)}>{String(r.id).padStart(2,'0')} · {r.name}</option>{/each}</select></label><label class="search">Find a puzzle<input bind:value={search} type="search" placeholder="Search names or rules…"/></label><fieldset class="layout-picker"><legend>PDF layout</legend><button type="button" aria-label="Portrait · one puzzle per page" aria-pressed={!printLandscape} class:active={!printLandscape} onclick={()=>printLandscape=false}><span class="page-icon portrait-icon"><b>1</b></span><span>Portrait</span></button><button type="button" aria-label="Landscape · two puzzles per page" aria-pressed={printLandscape} class:active={printLandscape} onclick={()=>printLandscape=true}><span class="page-icon landscape-icon"><b>1</b><b>2</b></span><span>Landscape</span></button></fieldset><div class="actions"><a href="/wsc2026/WSC2026IB.pdf" target="_blank" rel="noreferrer">Open booklet ↗</a></div></section>

   {#each roundSections as section (section.id)}<section class="round-section"><div class="round-heading"><h2>{String(section.id).padStart(2,'0')} / {section.name}</h2><p>{section.minutes ? section.minutes+' minutes · '+section.points+' points' : 'Team round'}</p>{#if section.teamRules}<p>{section.teamRules} <a href={'/wsc2026/WSC2026IB.pdf#page='+section.page} target="_blank" rel="noreferrer">Full round rules ↗</a>{#if section.id===15} · <a href="/wsc2026/?tab=shifted">Shifted Sudoku practice ↗</a>{/if}</p>{/if}</div><div class="puzzle-list">{#each section.entries as p (p.id)}<article class="puzzle-card"><div class="card-heading"><h2>{#if p.variantId!=='classic'||p.source!=='booklet'||!!section.teamRules}<button class="rules-toggle" aria-expanded={!!openRules[p.id]} aria-controls={'rules-'+p.id} onclick={()=>openRules={...openRules,[p.id]:!openRules[p.id]}}>{p.name}</button>{:else}{p.name}{/if}</h2>{#if p.points}<span class="points">{p.points} <small>PTS</small></span>{/if}</div>
    <div class="card-controls"><p class="eyebrow">{p.number?'#'+p.number:'PRACTICE'} · {section.name}{p.stage?' · '+p.stage:''}</p><div class="actions">{#if p.id==='r08-01'}<a href="/wsc2026/?tab=blind" onclick={e=>e.stopPropagation()}>Open Blind Pips practice ↗</a>{/if}{#if p.variantId==='star'}<a href="/solver/star/" onclick={e=>e.stopPropagation()}>Open Star solver ↗</a>{/if}{#if p.variantId==='flower'}<a href="/wsc2026/?tab=flower" onclick={e=>e.stopPropagation()}>Open Flower Sudoku tool ↗</a>{:else if p.variantId==='shifted'}<a href="/wsc2026/?tab=shifted" onclick={e=>e.stopPropagation()}>Open Shifted Sudoku tool ↗</a>{:else if p.round===3}<a href="/wsc2026/?tab=hundred" onclick={e=>e.stopPropagation()}>Hundred combinations ↗</a>{/if}{#if practiceFor(p).length}<button aria-expanded={!!openPuzzles[p.id]} aria-controls={'puzzles-'+p.id} onclick={(e)=>{e.stopPropagation();openPuzzles={...openPuzzles,[p.id]:!openPuzzles[p.id]};}}>Puzzles ({practiceFor(p).length}) {openPuzzles[p.id]?'▴':'▾'}</button>{/if}</div></div>
    {#if p.variantId!=='classic' || p.source!=='booklet' || section.teamRules}<div id={'rules-'+p.id} hidden={!openRules[p.id]} class="card-expanded"><p class="rules" hidden={p.round===2&&p.source==='booklet'}>{p.rules}</p>
 {#if p.source==='booklet'}{#if p.round===2}<SamuraiExample example={p.example} solution={p.solution}/>{:else}<img class="official" src={p.image} alt={p.name+': official example and solution'} loading="lazy"/>{/if}{/if}</div>{/if}
    {#if practiceFor(p).length}<div id={'puzzles-'+p.id} hidden={!openPuzzles[p.id]} class="puzzle-entries card-expanded">{#each practiceFor(p) as q,i}<div class="practice-entry">{#if q.puzzle_url&&playerUrl(q.puzzle_url)}<a href={playerUrl(q.puzzle_url)} target="_blank" rel="noopener noreferrer">{i+1}. {q.name} ↗</a>{:else}<details><summary>{i+1}. {q.name}</summary><img src={q.example} alt={q.name} loading="lazy"/>{#if q.solution}<details><summary>Reveal solution</summary><img src={q.solution} alt={q.name+' solution'} loading="lazy"/></details>{/if}</details>{/if}</div>{/each}</div>{/if}
</article>{/each}</div></section>{/each}
    {#if filtered.length===0}<section class="empty"><h2>No puzzles in this view.</h2><p>Try a different filter.</p></section>{/if}
  {:else if tab==='blind'}
   <BlindPipsPractice/>
  {:else if tab==='shifted'}
   <ShiftedSudokuTool initialView={new URLSearchParams(location.search).get('tab')==='circular'?'outer':'classic'}/>
  {:else if tab==='flower'}
   <FlowerRoundTool/>

  {:else if tab==='hundred'}
   <HundredCombinationsTool/>
  {/if}
 </main><footer><nav aria-label="Site links"><a href="/">SUDOTOKU</a><a href="/list/">Variant library ↗</a></nav>Examples © WSC 2026 organizing team and credited authors. Non-commercial practice only. <a href="/wsc2026/WSC2026IB.pdf" target="_blank" rel="noreferrer">WSC 2026 booklet v2</a></footer>
</div>
{#if printMode}<section class:landscape={printLandscape} class="print-area"><div class="pack-cover"><h1>WSC 2026 · Practice pack</h1><p>{activeRound?`Round ${activeRound.id}: ${activeRound.name}`:'All rounds'} · {new Date().toLocaleDateString()}</p></div>{#each printRoundSections as section}<article class="round-preview"><p class="eyebrow">ROUND {String(section.id).padStart(2,'0')}</p><h2>{section.name}</h2><p class="round-meta">{section.minutes ? section.minutes+' minutes · '+section.points+' points' : 'Team round'}</p><h3>Puzzle order</h3><ol>{#each section.catalogEntries as p}<li><span>#{p.number} · {p.name}</span><strong>{p.points||'—'} pts</strong></li>{/each}</ol>{#if section.id===2}<SamuraiRules/>{/if}</article><div class="print-puzzle-grid" class:round-two={section.id===2} class:round-eleven={section.id===11}>{#each printRows(section) as row}<div class="print-puzzle-row" class:samurai-row={section.id===2}>{#each row as p}<article class="print-puzzle" class:samurai={section.id===2} class:relay-grid={section.id===11}><div class="print-puzzle-heading"><h2>#{p.round}.{p.number||'P'} · {p.name} · {p.points||'—'} pts</h2><div class="time-box">TIME<span>____ : ____</span></div></div>{#if p.variantId!=='classic' || p.source!=='booklet'}<p>{p.rules}</p>{/if}{#if p.round===2&&p.source==='booklet'}<p class="samurai-print-key">Top left: No Three in a Line · Top right: Creasing<br/>Centre: Palindrome · Bottom left & right: Clone Along Line</p>{/if}{#if p.example}<img src={p.example} alt={p.name}/>{:else}<p>This composite example is available in the original booklet, PDF page {p.page}.</p>{/if}</article>{/each}</div>{/each}</div>{/each}<p class="small print-credit">WSC 2026 instruction booklet v2. Examples for non-commercial practice; rights remain with credited authors.</p></section>{/if}

{/if}
<style>
 main{display:flex;flex-direction:column}.tabs{order:0;margin-top:0}.puzzle-link{align-self:flex-end;font-size:13px;padding:8px 0}

 .rules-toggle{padding:0;border:0;background:transparent;text-align:left;font:inherit;color:inherit}.rules-toggle::after{content:"";position:absolute;inset:0;border-radius:10px}.puzzle-card{position:relative}.card-expanded,.card-controls .actions{position:relative;z-index:1}.rules-toggle:hover{background:transparent;color:#315e43}.rules-toggle:focus-visible{outline:2px solid #315e43;outline-offset:3px}
 .card-controls{display:flex;align-items:center;justify-content:space-between;gap:18px;min-width:0;overflow-x:auto}.card-controls .eyebrow{margin:0;letter-spacing:.4px;font-size:11px;white-space:nowrap}.card-controls .actions{flex-wrap:nowrap;gap:6px}.card-controls button{font-size:12px;padding:3px 8px;border-color:transparent;background:transparent;line-height:20px}.card-controls button:hover,.card-controls button[aria-expanded="true"]{background:#edf2e8}.card-expanded{padding-top:12px;margin-top:8px;border-top:1px solid #ecede7}.card-expanded[hidden]{display:none}.card-expanded .rules{margin:0}.card-expanded img{display:block;max-width:min(100%,720px);margin:auto}
 
 
 .layout-picker{display:flex;gap:6px;border:0;padding:0;margin:0}.layout-picker legend{font-size:12px;font-weight:600;margin-bottom:8px}.layout-picker button{display:flex;align-items:center;gap:7px;padding:5px 8px;font-size:11px}.layout-picker button.active{border-color:#315e43;background:#e8efdf}.page-icon{display:grid;border:1px solid #718071;background:white;color:#315e43;font-size:9px;font-weight:700}.portrait-icon{width:18px;height:24px;place-items:center}.landscape-icon{width:30px;height:20px;grid-template-columns:1fr 1fr;place-items:center}.landscape-icon b+ b{border-left:1px solid #c5cec4;width:100%;height:100%;display:grid;place-items:center}

 .password-page{max-width:480px;margin:12vh auto;padding:20px}.password-page h1{font-size:36px}.round-section{margin:36px 0;border-top:2px solid #b9c6b1;padding-top:8px}.puzzle-entries{margin:0}.practice-entry{border-top:1px solid #ecede7;padding:10px 0;display:flex;gap:12px;align-items:center;justify-content:space-between}
 :global(body){margin:0;background:#f5f4ef;color:#20382e;font-family:Inter,Arial,sans-serif;font-size:15px} :global(*){box-sizing:border-box} :global(button),:global(input),:global(select),:global(textarea){font:inherit} :global(button),:global(a){-webkit-tap-highlight-color:transparent}button{cursor:pointer;border:1px solid #c5cec4;background:#fff;color:#20382e;padding:10px 14px;border-radius:7px;white-space:nowrap}button:hover{background:#e8ede4}button:disabled{opacity:.5;cursor:wait}.primary{background:#244d3b;color:white;border-color:#244d3b}.primary:hover{background:#173b2b}a{color:#315e43}.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}main{max-width:1200px;margin:auto;padding:0 0 60px}.eyebrow{font-size:11px;letter-spacing:2px;font-weight:700;color:#6a7869}h1{font-size:clamp(34px,4.5vw,60px);font-weight:500;letter-spacing:-2px;margin:20px 0}.tabs{display:flex;gap:28px;margin-top:0;border-bottom:1px solid #d8ded4;overflow:auto}.tabs button{border:0;background:none;border-radius:0;padding:16px 0;color:#788171}.tabs button.active{border-bottom:3px solid #254c37;color:#20382e;font-weight:700}.toolbar{display:flex;gap:20px;align-items:end;margin:28px 0}.toolbar .search{flex:1}.toolbar .actions{margin-bottom:0}label{display:flex;flex-direction:column;gap:8px;font-size:12px;font-weight:600;margin-bottom:16px}.toolbar label{margin:0}input,select{border:1px solid #d2d8cd;border-radius:6px;padding:11px;background:white;min-width:0;color:#20382e}.small{font-size:12px;color:#74806d;line-height:1.7}.puzzle-list{display:grid;grid-template-columns:minmax(0,1fr);gap:8px}.puzzle-card{min-width:0;padding:12px 16px;background:#fff;border:1px solid #dce1d6;border-radius:10px;display:flex;flex-direction:column}.card-heading{display:flex;justify-content:space-between;align-items:center;gap:14px;min-width:0}.card-heading h2{margin:0;font-size:16px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;line-height:24px}.points{font-size:16px;color:#6a775d;white-space:nowrap}.points small{font-size:9px}.rules{color:#697467;font-size:14px;line-height:1.7;margin:0 0 18px}.puzzle-card details{margin-bottom:18px}summary{cursor:pointer;color:#456638;font-size:13px;padding:8px 0}img{max-width:100%;height:auto}.panel,.empty{background:#fff;border:1px solid #dce1d6;border-radius:10px;padding:28px;margin:22px 0}.empty{text-align:center}.panel p{color:#788171;line-height:1.6}.message{padding:16px;background:#e4ebdb;border-radius:6px;overflow-wrap:anywhere}.error{color:#9e332e;background:#fff0e9}.round-heading{margin:24px 0}.round-heading h2{font-weight:500}.round-heading p{color:#758171}footer{max-width:1200px;margin:auto;padding:20px 0 30px;border-top:1px solid #d8ded4;font-size:11px;color:#788171}footer nav{display:flex;align-items:center;gap:18px;flex-wrap:wrap;margin-bottom:16px}.print-area{display:none}
 @media(max-width:1260px){main,footer{margin-inline:30px}}@media(max-width:720px){main,footer{margin-inline:18px}.tabs{gap:24px}.toolbar{flex-wrap:wrap}.toolbar label{flex:1}.toolbar .actions{width:100%}.puzzle-list{grid-template-columns:1fr}.puzzle-card{padding:10px 12px}}
 @media print{ :global(body){background:white;color:black}.app-shell{display:none!important}.print-area{display:block;font-family:Arial,sans-serif}.print-area.landscape{page:wsc-landscape}.pack-cover{min-height:245mm;display:flex;flex-direction:column;justify-content:center;break-after:page}.print-area.landscape .pack-cover{min-height:170mm}.print-area h1{font-size:28px;letter-spacing:0}.print-area h2{font-size:18px}.round-preview{min-height:245mm;padding:20mm 12mm;break-before:page;break-after:page}.landscape .round-preview{min-height:170mm;padding:12mm 16mm}.round-preview h2{font-size:32px;margin:8mm 0 3mm}.round-preview .round-meta{font-size:15px}.round-preview h3{margin-top:16mm}.round-preview ol{padding:0;list-style:none;border-top:2px solid #222;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));column-gap:12mm}.round-preview li{display:flex;justify-content:space-between;gap:5mm;padding:3mm 0;border-bottom:1px solid #bbb;font-size:12px;break-inside:avoid}.print-puzzle-grid{display:grid;grid-template-columns:1fr;gap:0}.print-puzzle{min-height:245mm;padding:4mm 0;break-before:page;break-inside:avoid;overflow:hidden;display:flex;flex-direction:column}.print-puzzle:first-child{break-before:auto}.print-puzzle-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:8mm}.print-puzzle-heading h2{margin:2mm 0}.time-box{flex:0 0 30mm;height:16mm;border:1.5px solid #222;padding:2mm;font-size:8px;font-weight:700;text-align:center;letter-spacing:1px}.time-box span{display:block;font-size:14px;letter-spacing:10px;margin-left:10px}.print-puzzle img{display:block;width:170mm;height:190mm;margin:auto auto 3mm;object-fit:contain}.print-puzzle p{font-size:10pt;line-height:1.35}.landscape .print-puzzle-grid{grid-template-columns:1fr 1fr;gap:10mm;break-before:page}.landscape .print-puzzle{min-height:170mm;break-before:auto;border-right:1px solid #bbb;padding-right:5mm}.landscape .print-puzzle:nth-child(even){border-right:0;padding-right:0}.landscape .print-puzzle:nth-child(2n+3){break-before:page}.landscape .print-puzzle img{width:122mm;height:112mm}.print-puzzle-grid.round-two{display:block}.print-puzzle.samurai{page:wsc-portrait;min-height:245mm;border:0!important;padding:4mm 0!important}.print-puzzle.samurai img{width:185mm;height:210mm}.print-puzzle-grid.round-eleven .print-puzzle img{object-fit:contain}.print-credit{display:none}@page{size:A4 portrait;margin:15mm}@page wsc-landscape{size:A4 landscape;margin:12mm}@page wsc-portrait{size:A4 portrait;margin:10mm}}
 @media print{
  .print-puzzle-grid{display:block!important}
  .print-puzzle-row{display:grid;grid-template-columns:1fr;gap:0;break-before:page;break-inside:avoid}
  .landscape .print-puzzle-row{grid-template-columns:1fr 1fr;gap:10mm;page:wsc-landscape}
  .landscape .print-puzzle-row .print-puzzle{border-right:1px solid #bbb;padding-right:5mm}
  .landscape .print-puzzle-row .print-puzzle:last-child{border-right:0;padding-right:0}
  .print-puzzle-row.samurai-row{display:block;page:wsc-portrait}
  .print-puzzle-heading{position:relative;z-index:2;background:#fff}
  .time-box span{letter-spacing:0!important;margin:1mm 0 0!important;font-size:10px!important}
  .print-puzzle.samurai{height:260mm;min-height:260mm!important;max-height:260mm;box-sizing:border-box}
  .print-puzzle.samurai>p{display:block;font-size:9pt}.print-puzzle.samurai>p:not(.samurai-print-key){display:none}.print-puzzle.samurai .samurai-print-key{font-size:9pt;line-height:1.6;margin:3mm 0;text-align:center;flex-shrink:0}
  .print-puzzle.samurai img{width:190mm!important;max-width:100%;height:190mm!important;object-fit:contain;flex-shrink:0;margin:auto auto!important}
 }
</style>
