<script lang="ts">
 import { onDestroy } from 'svelte';
 let text='',result='',running=false,worker:Worker|null=null;
 async function template(){await import(/* @vite-ignore */ '/js/sudoku_variants/wsc_rules.js');await import(/* @vite-ignore */ '/js/wsc_topology.js');text=JSON.stringify((window as any).WscTopology.samurai(),null,2);result='Samurai topology loaded. Enter givens and the four variant rule sets before solving. This template contains only the overlapping Classic units.';}
 function solve(){try{const data=JSON.parse(text);worker?.terminate();worker=new Worker('/js/wsc_topology_worker.js');running=true;result='Searching…';worker.onmessage=e=>{result=e.data.error||JSON.stringify(e.data.result,null,2);running=false;worker?.terminate();};worker.onerror=()=>{result='Solver worker failed to load.';running=false;worker?.terminate();};worker.postMessage(data);}catch(e:any){result=e.message;}}
 function cancel(){worker?.terminate();running=false;result='Search cancelled.';}
 onDestroy(()=>worker?.terminate());
</script>
<section><h2>Nonstandard layout solver</h2><p>Samurai, Expanded, Star and the team-round layouts use explicit cell connections. Enter givens and every row, column and region; this tool does not transcribe the booklet images.</p><details><summary>Input format</summary><p><code>values</code>: digits in cell-index order, 0 for empty. <code>units</code>: one list of indices for each row, column and outlined region; digits cannot repeat within a unit. For Star, include both diagonal-row directions. For Expanded, continue rows over gaps and black cells. Samurai's overlapping cells share a single index. For each Pentagram, set <code>digitCount</code> to 9, list its eight-cell units, and put their unit indices in <code>sharedDigitSetGroups</code> so every unit uses the same eight digits.</p><p><code>grids</code>: optional 81-cell mappings with WSC <code>clues</code>. <code>clones</code>: cross-grid line pairs <code>&#123;"a":[0,1],"b":[90,91],"reversible":true&#125;</code>. The Samurai round additionally needs No Three in a Line (top left), Creasing (top right), Palindrome (centre) and Clone Along Line (bottom grids).</p><p>A result marked “limit” is incomplete and is not a uniqueness claim. Search runs in a cancellable worker.</p></details><button onclick={template}>Load Samurai layout template</button><label>Puzzle definition<textarea bind:value={text} rows="12" spellcheck="false" placeholder={'{"values":[0,0],"units":[[0,1]]}'}></textarea></label><button disabled={running||!text} onclick={solve}>Solve supplied layout</button>{#if running}<button onclick={cancel}>Cancel</button>{/if}<pre aria-live="polite">{result}</pre></section>
<style>section{padding:24px;background:#fff;border:1px solid #dce1d6;border-radius:10px;margin-top:30px}p{line-height:1.65;color:#697467}summary{cursor:pointer}button{padding:10px;background:#244d3b;color:white;border:0;border-radius:6px;margin:10px 8px 10px 0;cursor:pointer}label{display:block}textarea{display:block;width:100%;box-sizing:border-box;font:12px monospace;margin-top:8px;border:1px solid #ccd4c8;padding:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:420px;overflow:auto}</style>
